server:
  port: 7788
changzer:
  swagger:
    enabled: true #是否启用swagger
    title: 测试文档
    description: 在线文档
    basePackage: cn.changzer.controller
#    docket:
#      user:
#        title: 用户模块
#        base-package: cn.changzer.controller.user
#      menu:
#        title: 菜单模块
#        base-package: cn.changzer.controller.menu
